import React, { useState, useEffect } from 'react';
import { base44 } from '@/api/base44Client';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { AlertCircle, Download, Upload, FileText, CheckCircle2 } from 'lucide-react';
import { toast } from 'sonner';

export default function NDAWorkflow({ rfqId, buyerEmail, supplierEmail }) {
  const [nda, setNda] = useState(null);
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    loadNDA();
  }, []);

  const loadNDA = async () => {
    try {
      const currentUser = await base44.auth.me();
      setUser(currentUser);

      const ndas = await base44.entities.NDA.filter({
        rfq_id: rfqId,
        buyer_email: buyerEmail,
        supplier_email: supplierEmail
      });

      if (ndas.length > 0) {
        setNda(ndas[0]);
      }
    } catch (error) {
      console.error('Error loading NDA:', error);
    }
  };

  const downloadTemplate = () => {
    const template = `
NON-DISCLOSURE AGREEMENT (NDA)

This Non-Disclosure Agreement ("Agreement") is entered into as of [Date]

BETWEEN:
Buyer: [Buyer Company Name]
Address: [Buyer Address]

AND:
Supplier: [Supplier Company Name]
Address: [Supplier Address]

1. CONFIDENTIAL INFORMATION
The parties agree to maintain confidentiality regarding all information exchanged through the Mi-Proc platform related to RFQ #${rfqId}.

2. OBLIGATIONS
Both parties agree to:
- Keep all shared information confidential
- Not disclose to third parties without written consent
- Use information solely for business evaluation purposes

3. TERM
This agreement remains in effect for 2 years from the date of signing.

4. SIGNATURES
Buyer Signature: ___________________ Date: ___________
Supplier Signature: _________________ Date: ___________

Generated by Mi-Proc Platform
    `;

    const blob = new Blob([template], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = \`NDA_Template_RFQ_\${rfqId}.txt\`;
    document.body.appendChild(a);
    a.click();
    URL.revokeObjectURL(url);
    a.remove();
  };

  const handleUpload = async (file) => {
    setLoading(true);
    try {
      const { file_url } = await base44.integrations.Core.UploadFile({ file });

      const expiresAt = new Date();
      expiresAt.setFullYear(expiresAt.getFullYear() + 2);

      await base44.entities.NDA.create({
        rfq_id: rfqId,
        buyer_email: buyerEmail,
        supplier_email: supplierEmail,
        document_url: file_url,
        status: 'pending',
        expires_at: expiresAt.toISOString()
      });

      toast.success('NDA uploaded successfully');
      loadNDA();
    } catch (error) {
      toast.error('Failed to upload NDA');
    } finally {
      setLoading(false);
    }
  };

  const handleSign = async () => {
    setLoading(true);
    try {
      const isBuyer = user.email === buyerEmail;
      const updateData = {
        [isBuyer ? 'buyer_signed' : 'supplier_signed']: true,
        [isBuyer ? 'buyer_signed_date' : 'supplier_signed_date']: new Date().toISOString()
      };

      const bothSigned = isBuyer ? nda.supplier_signed : nda.buyer_signed;
      if (bothSigned) {
        updateData.status = 'fully_signed';
      } else {
        updateData.status = 'partially_signed';
      }

      await base44.entities.NDA.update(nda.id, updateData);
      toast.success('NDA signed successfully');
      loadNDA();
    } catch (error) {
      toast.error('Failed to sign NDA');
    } finally {
      setLoading(false);
    }
  };

  const isBuyer = user?.email === buyerEmail;
  const hasSigned = isBuyer ? nda?.buyer_signed : nda?.supplier_signed;
  const otherPartySigned = isBuyer ? nda?.supplier_signed : nda?.buyer_signed;

  return (
    <Card className="border-2 border-amber-200 bg-amber-50">
      <CardContent className="p-6">
        <div className="flex items-start gap-4">
          <div className="w-12 h-12 bg-amber-100 rounded-full flex items-center justify-center flex-shrink-0">
            <FileText className="h-6 w-6 text-amber-600" />
          </div>
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-2">
              <h3 className="font-semibold text-slate-900">Non-Disclosure Agreement (NDA)</h3>
              {nda && (
                <Badge className={
                  nda.status === 'fully_signed' ? 'bg-green-100 text-green-700' :
                  nda.status === 'partially_signed' ? 'bg-yellow-100 text-yellow-700' :
                  'bg-slate-100 text-slate-700'
                }>
                  {nda.status.replace('_', ' ')}
                </Badge>
              )}
            </div>

            {!nda ? (
              <>
                <p className="text-sm text-slate-600 mb-4">
                  Download the NDA template, fill it out, and upload the signed document.
                </p>
                <div className="flex gap-3">
                  <Button 
                    variant="outline" 
                    size="sm" 
                    onClick={downloadTemplate}
                    className="gap-2"
                  >
                    <Download className="h-4 w-4" />
                    Download Template
                  </Button>
                  <label>
                    <Button variant="outline" size="sm" className="gap-2" disabled={loading}>
                      <Upload className="h-4 w-4" />
                      Upload Signed NDA
                    </Button>
                    <input
                      type="file"
                      className="hidden"
                      accept=".pdf,.doc,.docx"
                      onChange={(e) => e.target.files[0] && handleUpload(e.target.files[0])}
                    />
                  </label>
                </div>
              </>
            ) : (
              <>
                <div className="space-y-2 mb-4">
                  <div className="flex items-center gap-2 text-sm">
                    {nda.buyer_signed ? (
                      <CheckCircle2 className="h-4 w-4 text-green-600" />
                    ) : (
                      <AlertCircle className="h-4 w-4 text-amber-600" />
                    )}
                    <span className={nda.buyer_signed ? 'text-green-700' : 'text-slate-600'}>
                      Buyer {nda.buyer_signed ? 'signed' : 'pending'}
                    </span>
                  </div>
                  <div className="flex items-center gap-2 text-sm">
                    {nda.supplier_signed ? (
                      <CheckCircle2 className="h-4 w-4 text-green-600" />
                    ) : (
                      <AlertCircle className="h-4 w-4 text-amber-600" />
                    )}
                    <span className={nda.supplier_signed ? 'text-green-700' : 'text-slate-600'}>
                      Supplier {nda.supplier_signed ? 'signed' : 'pending'}
                    </span>
                  </div>
                </div>

                <div className="flex gap-3">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => window.open(nda.document_url, '_blank')}
                    className="gap-2"
                  >
                    <Download className="h-4 w-4" />
                    Download NDA
                  </Button>
                  {!hasSigned && (
                    <Button
                      size="sm"
                      onClick={handleSign}
                      disabled={loading}
                      className="bg-green-600 hover:bg-green-700 gap-2"
                    >
                      <CheckCircle2 className="h-4 w-4" />
                      Sign NDA
                    </Button>
                  )}
                </div>
              </>
            )}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}